-- Идемпотентность выпуска полисов Centrum Air (ТЗ п. 7.3).
-- Выполнить перед запуском приложения: spring.jpa.hibernate.ddl-auto = validate.

CREATE TABLE INS_CENTRUM_AIR_IDEMPOTENCY (
    ID                  NUMBER(19)     NOT NULL,
    IDEMPOTENCY_KEY     VARCHAR2(255)  NOT NULL,
    PNR                 VARCHAR2(50)   NOT NULL,
    PRODUCT_FINGERPRINT VARCHAR2(255)  NOT NULL,
    REQUEST_HASH        VARCHAR2(64)   NOT NULL,
    STATUS              VARCHAR2(20)   NOT NULL,
    BOOKING_ID          NUMBER(19),
    RESPONSE_JSON       CLOB,
    ERROR_MESSAGE       VARCHAR2(1000),
    CREATED_AT          TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT          TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_INS_CA_IDEMPOTENCY PRIMARY KEY (ID),
    CONSTRAINT UQ_INS_CA_IDEMPOTENCY_KEY UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT CK_INS_CA_IDEMPOTENCY_STATUS
        CHECK (STATUS IN ('IN_PROGRESS', 'PARTIAL', 'COMPLETED', 'FAILED'))
);

-- Поиск активных дублей по брони и набору продуктов (ТЗ п. 7.6.5).
CREATE INDEX IX_INS_CA_IDEMP_PNR ON INS_CENTRUM_AIR_IDEMPOTENCY (PNR, PRODUCT_FINGERPRINT, STATUS);

CREATE SEQUENCE SEQ_INS_CENTRUM_AIR_IDEMPOTENCY START WITH 1 INCREMENT BY 1 NOCACHE;

-- Полисы, уже выпущенные в рамках заявки: повтор довыпускает только недостающие.
CREATE TABLE INS_CENTRUM_AIR_IDEMP_POLICY (
    ID             NUMBER(19) NOT NULL,
    IDEMPOTENCY_ID NUMBER(19) NOT NULL,
    POLICY_GROUP   NUMBER(3)  NOT NULL,
    CONTRACT_ID    NUMBER(19) NOT NULL,
    POLICY_ID      NUMBER(19) NOT NULL,
    CREATED_AT     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_INS_CA_IDEMP_POLICY PRIMARY KEY (ID),
    CONSTRAINT UQ_INS_CA_IDEMP_POLICY_GROUP UNIQUE (IDEMPOTENCY_ID, POLICY_GROUP),
    CONSTRAINT FK_INS_CA_IDEMP_POLICY FOREIGN KEY (IDEMPOTENCY_ID)
        REFERENCES INS_CENTRUM_AIR_IDEMPOTENCY (ID)
);

CREATE SEQUENCE SEQ_INS_CENTRUM_AIR_IDEMP_POL START WITH 1 INCREMENT BY 1 NOCACHE;
